apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: notes-app-rules
  labels:
    prometheus: k8s
spec:
  groups:
    - name: notes-app.rules
      rules:
        - alert: HighCPUUtilization
          expr: |
            sum(rate(container_cpu_usage_seconds_total{pod=~"notes-app-.*"}[2m])) by (deployment) / sum(kube_pod_container_resource_limits_cpu_cores{pod=~"notes-app-.*"}) by (deployment) * 100 > 80
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "High CPU on notes-app ({{ $labels.deployment }})"
            description: "CPU usage > 80% for more than 5 minutes."
